# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ⚙
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install node_modules 📦
        run: npm ci    

      - name: Build 🚀
        run: echo 'test'
